import { CommonModule } from '@angular/common';
import { ChangeDetectorRef, Component, OnInit } from '@angular/core';
import { ActivatedRoute, Router, RouterLink } from '@angular/router';
import { jsPDF } from 'jspdf';
import { AnalysisServices } from '../../services/analysis-services';

@Component({
  selector: 'app-analysis-page',
  imports: [CommonModule, RouterLink],
  templateUrl: './analysis-page.html',
  styleUrl: './analysis-page.css',
})
export class AnalysisPage implements OnInit {
  matchPercentage = 0;
  matchedSkills: string[] = [];
  missingSkills: string[] = [];
  suggestions: string[] = [];
  analysisId = '';

  constructor(private router: Router, private analysisService: AnalysisServices, private route: ActivatedRoute, private cdr: ChangeDetectorRef) { }
  ngOnInit() {
    this.analysisId = this.route.snapshot.paramMap.get('id')!;

    if (!this.analysisId) {
      this.router.navigate(['/dashboard']);
      return;
    }

    this.loadAnalysis();
  }
  loadAnalysis() {
    this.analysisService.getAnalysisById(this.analysisId)
      .subscribe((res: any) => {
        console.log(res);
        this.matchPercentage = res.matchPercentage || 0;
        this.matchedSkills = res.matchedSkills || [];
        this.missingSkills = res.missingSkills || [];
        this.generateSuggestions();
        this.cdr.detectChanges();
      }, err => {
        console.error(err);
        this.router.navigate(['/dashboard']);
      });
  }
  generateSuggestions() {
    this.suggestions = this.missingSkills.map(
      s => `Consider adding ${s} to strengthen your resume.`
    );
  }
  downloadReport() {
    const doc = new jsPDF();
    let y = 20;

    // ===== Title =====
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(20);
    doc.text('Resume Analysis Report', 105, y, { align: 'center' });

    y += 10;
    doc.setFontSize(11);
    doc.setFont('helvetica', 'normal');
    const today = new Date();
    const formattedDate = today.toLocaleDateString('en-GB', {
      day: '2-digit',
      month: 'long',
      year: 'numeric'
    });

    doc.text(`Generated on: ${formattedDate}`, 105, y, { align: 'center' });

    // ===== Match Summary Box =====
    y += 15;
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(14);
    doc.text('Match Summary', 14, y);

    y += 5;
    doc.setDrawColor(24, 210, 124);
    doc.setLineWidth(0.5);
    doc.rect(14, y, 180, 18);

    doc.setFont('helvetica', 'normal');
    doc.setFontSize(12);
    doc.text(`Match Percentage: ${this.matchPercentage}%`, 20, y + 12);

    // ===== Matched Skills =====
    y += 30;
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(13);
    doc.text('Matched Skills', 14, y);

    y += 8;
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(11);

    if (this.matchedSkills.length === 0) {
      doc.text('None', 18, y);
      y += 7;
    } else {
      this.matchedSkills.forEach(skill => {
        doc.text(`• ${skill}`, 18, y);
        y += 7;
      });
    }

    // ===== Missing Skills =====
    y += 5;
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(13);
    doc.text('Missing Skills', 14, y);

    y += 8;
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(11);

    if (this.missingSkills.length === 0) {
      doc.text('None', 18, y);
      y += 7;
    } else {
      this.missingSkills.forEach(skill => {
        doc.text(`• ${skill}`, 18, y);
        y += 7;
      });
    }

    // ===== AI Suggestions =====
    y += 5;
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(13);
    doc.text('AI Suggestions', 14, y);

    y += 8;
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(11);

    if (this.suggestions.length === 0) {
      doc.text('No suggestions available.', 18, y);
      y += 7;
    } else {
      this.suggestions.forEach(suggestion => {
        doc.text(`• ${suggestion}`, 18, y, { maxWidth: 170 });
        y += 8;
      });
    }

    // ===== Footer =====
    doc.setFontSize(9);
    doc.setTextColor(150);
    doc.text(
      'Generated by AI Powered Resume Analyzer',
      105,
      290,
      { align: 'center' }
    );

    doc.save('resume-analysis-report.pdf');
  }

  // downloadReport() {
  //   const doc = new jsPDF();

  //   doc.setFontSize(18);
  //   doc.text('Resume Analysis Report', 14, 20);

  //   doc.setFontSize(12);
  //   doc.text(`Match Percentage: ${this.matchPercentage}%`, 14, 35);

  //   doc.text('Matched Skills:', 14, 50);
  //   this.matchedSkills.forEach((s, i) => {
  //     doc.text(`- ${s}`, 18, 60 + i * 8);
  //   });

  //   let y = 60 + this.matchedSkills.length * 8 + 10;

  //   doc.text('Missing Skills:', 14, y);
  //   this.missingSkills.forEach((s, i) => {
  //     doc.text(`- ${s}`, 18, y + 10 + i * 8);
  //   });

  //   y += 20 + this.missingSkills.length * 8;

  //   doc.text('AI Suggestions:', 14, y);
  //   this.suggestions.forEach((s, i) => {
  //     doc.text(`- ${s}`, 18, y + 10 + i * 8);
  //   });

  //   doc.save('resume-analysis-report.pdf');
  // }

}
